
all:
	javac -classpath .:../lib/dom4j-1.6.1/dom4j-1.6.1.jar NeuroGen.java
	javac -classpath .:../lib/dom4j-1.6.1/dom4j-1.6.1.jar Population.java
	javac -classpath .:../lib/dom4j-1.6.1/dom4j-1.6.1.jar Circuit.java
	
